### ISSUE TITLE
Duplicate File Issue

### ISSUE THREAD

**Issue by cvaught** [aparajita/Cup#3]
I have found an issue where when uploading two or more files. Basically I need to pass additional form data within the upload request. To do this, I added the following code:

    var formData = new FormData();
    formData.append('test', 'value');

    var options = [uploader1 options];
    options.formData = formData;
    [uploader1 setOptions:options];

If I take the Cup Demo app and simply add the above to applicationDidFinishLaunching then anytime you upload two or more files the new request for each file continues to also contain the previous files that have already been uploaded. Thus, if you upload two files, the first request contains the first file and the second request contains the first and the second. This results in three files being uploaded.

In the jQuery file upload [docs](https://github.com/blueimp/jQuery-File-Upload/wiki/How-to-submit-additional-form-data#user-content-adding-additional-form-data-programmatically) it says you can add additional form data programmatically in this manner.

To verify, I took the demo jQuery application that is provided and simply added the formData variable that I added above to the main.j file. This is shown below:

    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload({
        url: '/upload/gcs/',
        formData: {test: 'value'}
    });

This works just as it should. The parameter is included and the request only contains the file being uploaded in each request.

Any idea what is causing this behavior when using Cup?

**Comment by aparajita** [comment]
What happens if you pass a simple object instead of a FormData? That's how it's supposed to be done according to the jQuery File Upload docs. In other words:

```objj
var options = [uploader1 options];
options.formData = { test: "value" };
[uploader1 setOptions:options];
```

**Comment by cvaught** [comment]
Thanks aparjita. That fixed it. Not sure why I thought I should be using a FormData object.
